# Generated by Django 4.0.6 on 2022-08-05 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('None', 'None'), ('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.IntegerField()),
                ('sales', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='photos/products')),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('Medium', 'Medium'), ('Large', 'Large'), ('Small', 'Small'), ('Regular', 'Regular')], max_length=100)),
                ('price', models.IntegerField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmenu.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='AddOns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_ons', models.CharField(choices=[('Cheesy', 'Cheesy'), ('Peri Peri', 'Peri Peri'), ('Sauces', 'Sauces'), ('Flavours', 'Flavours')], max_length=50)),
                ('variation', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmenu.menuitem')),
            ],
            options={
                'verbose_name': 'addons',
                'verbose_name_plural': 'add ons',
            },
        ),
    ]
