# Generated by Django 4.0.6 on 2022-08-05 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodmenu', '0001_initial'),
        ('table', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=250)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('addon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodmenu.addons')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodmenu.menuitem')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodmenu.size')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.table')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
        ),
    ]
