# Generated by Django 4.0.6 on 2022-08-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField()),
                ('status', models.CharField(choices=[('unoccupied', 'unoccupied'), ('occupied', 'occupied')], max_length=50)),
            ],
        ),
    ]
